# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-jmdsw5pfpr-FRL-OwJIbgk5k2OpphE
"""

resposta = input("Deseja continuar no sistema? (Sim/Não): ")

if resposta.lower() == "sim":
    print("Continuando...")
else:
    print("Encerrando...")

uf = input("Digite a sigla do seu estado (ex: sp, rj, mg): ")

3
uf_padronizada = uf.upper()

print(f"Estado cadastrado: {uf_padronizada}")

cupom_valido = "DESCONTO10"
cupom_usuario = input("Digite o seu cupom promocional: ")

if cupom_usuario.upper() == cupom_valido:
    print("Cupom aplicado com sucesso!")
else:
    print("Cupom inválido.")

nome = input("Digite o seu primeiro nome: ")

nome_limpo = nome.strip()

print(f"Nome limpo: {nome_limpo}")
print(f"Quantidade de caracteres: {len(nome_limpo)}")

email = input("Digite seu e-mail: ").strip()

if email == "":
    print("Erro: O campo e-mail não pode ficar em branco!")
    else:
        print("E-mail cadastrado!")

usuario_correto = "aluno@escola.com"

login = input("Digite seu login: ").strip().lower()

if login == usuario_correto:
    print("Login realizado com sucesso!")
    else:
        print("Login ou usuário incorreto!")